services:
  # Main bot service
  lloyd:
    container_name: lloyd
    build: .
    volumes:
      - /mnt/AppStorage/lloyd-bot/configs:/app/configs/ # Config files
    restart: unless-stopped

  # Auto updater
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 60
