//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/AppsIWillNeverFinish/LloydWarningSystem.Net/LloydWarningSystem.Net/FinderBot/Commands/Compiler/LScript/ANTLR/LScriptParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ILScriptParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] LScriptParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignment([NotNull] LScriptParser.VariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] LScriptParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDefinition([NotNull] LScriptParser.VariableDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.routineDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutineDefinition([NotNull] LScriptParser.RoutineDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.routineCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutineCall([NotNull] LScriptParser.RoutineCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LScriptParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExpression([NotNull] LScriptParser.IdentifierExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>stringLiteralExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteralExpression([NotNull] LScriptParser.StringLiteralExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableAssignmentExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignmentExpression([NotNull] LScriptParser.VariableAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>routineDefinitionExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutineDefinitionExpression([NotNull] LScriptParser.RoutineDefinitionExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>routineCallExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoutineCallExpression([NotNull] LScriptParser.RoutineCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockExpression</c>
	/// labeled alternative in <see cref="LScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockExpression([NotNull] LScriptParser.BlockExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] LScriptParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LScriptParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] LScriptParser.ParameterListContext context);
}
